# Generated by Django 4.0.3 on 2022-03-28 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoContribuyente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Tipo de Contribuyente',
                'verbose_name_plural': 'Tipo de Contribuyentes',
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, verbose_name='Código')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Tipo de Documento',
                'verbose_name_plural': 'Tipo de Documentos',
            },
        ),
        migrations.CreateModel(
            name='Entidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_documento', models.CharField(max_length=40, verbose_name='Numero de documento')),
                ('razon_social', models.CharField(max_length=40, verbose_name='Razón Social')),
                ('nombre_comercial', models.CharField(max_length=150, verbose_name='Nombre Comercial')),
                ('telefono', models.CharField(max_length=50, verbose_name='Teléfono')),
                ('direccion', models.TextField(verbose_name='Dirección')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('tipo_contribuyente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tipocontribuyente', verbose_name='Tipo de Contribuyente')),
                ('tipo_documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tipodocumento', verbose_name='Tipo de documento')),
            ],
            options={
                'verbose_name': 'Entidad',
                'verbose_name_plural': 'Entidades',
            },
        ),
    ]
